spring.application.name=cryptoapp-wallet-api
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:cryptoapp}
spring.datasource.username=${POSTGRES_USER:cryptoapp}
spring.datasource.password=${POSTGRES_PASSWORD:cryptoapp}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
